#!/usr/bin/env bash
#creates a file myscript.pid and loops infitnitely

trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
echo $$ > /var/run/myscript.pid
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
